### ISSUE TITLE
You're doing God's work

### ISSUE THREAD

**Issue by dvmazur** [shandalov/palace#1]
Мы с @ivanchgeek искренне рады видеть, что традиции кибер-диссидентства сохранились в гимназии даже в такое нелёгкое время.

Great work,
Keep it up,
Proud of you!

**Comment by precious-void** [comment]
Выглядит шикарно, но настройте плес github pages!

**Comment by dvmazur** [comment]
> Выглядит шикарно, но настройте плес github pages!

Ребята таки [настроили](https://shandalov.github.io/palace/)!

**Comment by Sinoosoida** [comment]
Аквадискотеки, с тех пор как Коля Цибин выпустился, к сожалению, в дворце не проводятся :(
